[mypy]
strict = True
plugins = sqlalchemy.ext.mypy.plugin
exclude = (test_|security_tests/)

[mypy-srp]
ignore_missing_imports = True

[mypy-oqs]
ignore_missing_imports = True

[mypy-sqlcipher3]
ignore_missing_imports = True

[mypy-sqlcipher3.*]
ignore_missing_imports = True
